/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package triplepane;


import java.awt.Font;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.JLabel;
import java.awt.event.*;
import java.util.ArrayList;

/**
 *
 * @author jcalvert
 */
public class MainFrame extends javax.swing.JFrame {
    public static Map M;
    public static TriplePane TP;
    public static Settlement SS;
    public String input;
    public static int YEAR = 1000;
    public static Boolean LOST = false;      
    public ArrayList Armies;
    
    
    public MainFrame() {
        setVisible(true);
        initComponents();
        Narra.setEditable(false);
        Settlement SS = new Settlement(this);
        M = new Map(this);
        Armies = new ArrayList();
        add(M);
        TP = new TriplePane(this,M,SS);
        TP.intro();
        
        SettName.setFont(new Font("arial",Font.BOLD,16));        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(480,480);
        setLocationRelativeTo(null);
        setTitle("Jhethria");
        setResizable(false);
        setVisible(true);
    }
    
    
    
    public static void MakeGUI(){
        MainFrame MF = new MainFrame();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Narra = new javax.swing.JTextArea();
        SettName = new javax.swing.JLabel();
        SettLevel = new javax.swing.JLabel();
        SettPop = new javax.swing.JLabel();
        SettFort = new javax.swing.JLabel();
        SettPros = new javax.swing.JLabel();
        SettFarms = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SettGarr = new javax.swing.JLabel();
        SettFood = new javax.swing.JLabel();
        SettGold = new javax.swing.JLabel();
        Edit = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        SettYEAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Narra.setColumns(20);
        Narra.setLineWrap(true);
        Narra.setRows(5);
        Narra.setToolTipText("");
        jScrollPane1.setViewportView(Narra);

        SettName.setText("Settlement Name");

        SettLevel.setText("Level:");

        SettPop.setText("Population:");

        SettFort.setText("Fortification:");

        SettPros.setText("Prosperity:");

        SettFarms.setText("Farms:");

        SettGarr.setText("Garrison:");

        SettFood.setText("Food:");

        SettGold.setText("Gold:");

        Edit.setPreferredSize(new java.awt.Dimension(59, 30));
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        SettYEAR.setText("Year 1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SettName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(SettYEAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SettLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettPop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettFort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettFarms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettPros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SettGarr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettFood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettGold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SettName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettYEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettPop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettFort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettFarms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettPros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettGarr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettGold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        
        if(LOST == true) {
            Narra.append("You have died!");
            ActionListener[] al = Edit.getActionListeners();
            Edit.removeActionListener(al[0]);
            return;
        }
        
        input = Edit.getText();        
        if(input.equals("")) Narra.append("Skip turn.");
        Narra.append(input + "\n");
        Edit.setText("");
        TP.doStuff(input);
        
        SettYEAR.setText("Year: " + Integer.toString(YEAR));
        
        
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
                MakeGUI();
            }
        });
    }
    
    public String getLine(){      
        return input;
    }
    
    public void writeNarra(String s){
        System.out.println(s);
        Narra.append(s+"\n");
    }
    
    public void setName(String s){
        SettName.setText(s);
    }
    public void setLevel(String s){
        SettLevel.setText(s);
    }
    public void setPop(String s){
        SettPop.setText(s);
    }
    public void setFort(String s){
        SettFort.setText(s);
    }
    public void setFarms(String s){
        SettFarms.setText(s);
    }
    public void setPros(String s){
        SettPros.setText(s);
    }
    public void setGarr(String s){
        SettGarr.setText(s);
    }
    public void setFood(String s){
        SettFood.setText(s);
    }
    public void setGold(String s){
        SettGold.setText(s);
    }
    public ArrayList getArmies() {
        return Armies;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Edit;
    private javax.swing.JTextArea Narra;
    private javax.swing.JLabel SettFarms;
    private javax.swing.JLabel SettFood;
    private javax.swing.JLabel SettFort;
    private javax.swing.JLabel SettGarr;
    private javax.swing.JLabel SettGold;
    private javax.swing.JLabel SettLevel;
    private javax.swing.JLabel SettName;
    private javax.swing.JLabel SettPop;
    private javax.swing.JLabel SettPros;
    private javax.swing.JLabel SettYEAR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
